language: android

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android

android:
  components:
    - build-tools-23.0.1
    - android-23

env:
  global:
  - secure: "jAsB/ADbOrw9ATjWGkKUEX6V5NSEt/cPg1wlEYQ5sBh8cBSXGvKLKN/5/Ccb9Zn0/1ikSrJ47D0HfH7CAiL5V4Mpakl7bZyoF7gZzXWvkrimAgP6wLl7IqT06z7h8c/vH7b+MB3ZJNDZhxih5v1dv2OT6IauIHoWHfMgfDfbwZNSxGMUgOcx5kxo/N2kwbJXWKWp/eGaWjWILxvT7YGO19A3h7eBvJeWfoaz+k51xSGl+qZWC0T+q3u3EBEL+/oMWuMyQfPhEQAlH8LUwQqB1ruVKaXE2l922L7ClsZwUVLI83DQ81AA/AZEq3Sjek5Wh9xSnjBI/QYz5560aE5L9O3C5W08D14WxXrXfwnEUIb+mVFCrjK8RBM4PxA0lDQQLApgE1SEWQH1e995jNuoEGOnPWinq8k2Zf2sMmp9/f9h1RHKYrU2MxJ3de3//gQbfFsw1WiHh2K5jCkBxxVhsFssB90joiMx+cDwp5JboVU5GkJZ0i6tOC9Q23Qk+G8q95gbspOxsCjHxpYBF8PtBKpimon+1EiXbGN1VirxkAs7hw8B9cqL6q6rVkXWFLuqt23CqdUan5sZhIoByjD7ZJTytQQI+bAXJ11bc2+KNt2gI4leSwDdmP46VQetVNrGZK/76JEBxu8t0IZ3nUaokQCx4Gnk6RIpIst2B/QmXxk="
  - secure: "KauEB0AMj36lDNPxMInU9xyKqtI9RptCTW5mH7Qd/Um/6eJbYj9LgPZU+efwuboT6dicHe/YDu+mc0Ms57OdW6LH32cgHrwj/42ZTkSgrrBK1jxXRPNODYJirFI2y8Yo+7Yz2t4MFHMLJOY9OoSQMWF3qsMVyab0XI4U3YVlQiTmznyjvYm8+dJxqVaWtgy0+GGRwwiRZ/k972MUx2L9j+Npf75U7PUrN7FqjU0Rn3VRraz10/msMkkV8mlaj1Lp7uMMW57AbV0k3HmxGctgMtN/eq1saiTK8ysBArigdgz0TZyAog2oERyZ5nL+Fju+5QelNsOl/7IEoZKphjhn9duzAkbXSaSCWORIgKrTQ5+VAg1KND/6Wn+F54xb0b7FFHqe/Gp4/pF8o45+Lj5ICaPDG+GOKeZxoiNB69qN/YUnEgMtrknb7MypxN+dWIBNdNJvhaTCPXgH5mbLQiq01c7s+DLnD3cLHZR7x5DdlJPQJWuw/3fxERZdo2R3J1sh7dPA1yWvXRrXLnKV5u3th1m6lc3OwCa+SRfPYqBzSrzxDTc81cxUWdI+lLYcH6k6D00j8o1tne84lfG8I+a4LCoEUCLKeGTPv6m5jPoBR/vIfcVCMvbwR4YAb7uNQh4DjDmbigAtTdGHWOwjstlNy8ma5W5pt/i8p1A7YO+k5B8="
  - JAVA_OPTS=-XX:MaxPermSize=1024m

notifications:
  email: false

install:
- TERM=dumb ./gradlew -q -s clean assemble

script:
- TERM=dumb ./gradlew -s --continue check jacocoTestReport install integrationTests

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./scripts/deploy_to_maven.sh

notifications:
  email: false
  
